alias: Refresh Panels And Graph
description: Refresh panels and graph on selection change
triggers:
  - entity_id:
      - input_datetime.timelapse_day_picker
      - input_number.timelapse_hour_slider
      - input_boolean.power_panels
      - input_boolean.latest_panels
      - input_boolean.timelapse_panels
    trigger: state
  - trigger: time_pattern
    minutes: "5"
  - trigger: time_pattern
    minutes: "10"
  - trigger: time_pattern
    minutes: "15"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ trigger.entity_id in [
                'input_boolean.latest_panels',
              ] }}
        sequence:
          - data:
              entity_id: input_boolean.timelapse_panels
            action: input_boolean.turn_off
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ trigger.entity_id in [
                'input_datetime.timelapse_day_picker',
                'input_number.timelapse_hour_slider',
              ] }}
        sequence:
          - data:
              entity_id: input_boolean.latest_panels
            action: input_boolean.turn_off
  - variables:
      mode: |-
        {% if is_state('input_boolean.latest_panels', 'on') and
              is_state('input_boolean.power_panels', 'off') %}
          live
        {% elif is_state('input_boolean.power_panels', 'on') %}
          power
        {% else %}
          energy
        {% endif %}
      hour: "{{ states('input_number.timelapse_hour_slider') | int }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ mode == 'live' }}"
        sequence:
          - data:
              entity_id: input_datetime.timelapse_day_picker
              date: "{{ now().date().isoformat() }}"
            action: input_datetime.set_datetime
          - wait_template: >-
              {{ states('input_datetime.timelapse_day_picker')[:10] ==
              now().date().isoformat() }}
            timeout: "00:00:01"
      - conditions:
          - condition: template
            value_template: "{{ mode == 'power' }}"
          - condition: state
            entity_id: input_boolean.latest_panels
            state: "on"
        sequence:
          - data:
              date: "{{ now().date().isoformat() }}"
            action: input_datetime.set_datetime
            target:
              entity_id: input_datetime.timelapse_day_picker
          - wait_template: >-
              {{ states('input_datetime.timelapse_day_picker')[:10] ==
              now().date().isoformat() }}
            timeout: "00:00:01"
  - variables:
      day: "{{ states('input_datetime.timelapse_day_picker')[:10] }}"
  - data:
      day: "{{ day }}"
      hour: "{{ hour }}"
      mode: "{{ mode }}"
    action: shell_command.query_panels
  - data:
      entity_id:
        - sensor.timelapse_power_graph
    action: homeassistant.update_entity
  - data:
      entity_id:
        - sensor.timelapse_power_panels
    action: homeassistant.update_entity
mode: single
