alias: Refresh Graph on Live
description: Refresh Graph on Live
triggers:
  - minutes: /5
    trigger: time_pattern
conditions:
  - condition: state
    entity_id: input_boolean.latest_panels
    state: "on"
actions:
  - variables:
      mode: |-
        {% if is_state('input_boolean.latest_panels', 'on') and
              is_state('input_boolean.power_panels', 'off') %}
          live
        {% elif is_state('input_boolean.power_panels', 'on') %}
          power
        {% else %}
          energy
        {% endif %}
      hour: "{{ states('input_number.timelapse_hour_slider') | int }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ mode == 'live' }}"
        sequence:
          - data:
              entity_id: input_datetime.timelapse_day_picker
              date: "{{ now().date().isoformat() }}"
            action: input_datetime.set_datetime
          - wait_template: >-
              {{ states('input_datetime.timelapse_day_picker')[:10] ==
              now().date().isoformat() }}
            timeout: "00:00:10"
  - variables:
      day: "{{ states('input_datetime.timelapse_day_picker')[:10] }}"
  - data:
      day: "{{ day }}"
      hour: "{{ hour }}"
      mode: "{{ mode }}"
    action: shell_command.query_panels
  - data:
      entity_id: sensor.timelapse_power_graph
    action: homeassistant.update_entity
  - data:
      entity_id: sensor.timelapse_power_panels
    action: homeassistant.update_entity
mode: single
