#INFLUXBD
influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state

### TIME OF DAY SELECTION
input_number:
  timelapse_hour_slider:
    name: Hour of Day
    min: 0
    max: 24
    step: 1
    unit_of_measurement: h
    icon: mdi:clock-outline

### DATE SELECTION
input_datetime:
  timelapse_day_picker:
    name: Select Day
    has_date: true
    has_time: false
    icon: mdi:calendar

input_boolean:
  latest_panels:
    name: Latest Panels   ### "LIVE" LATEST DATA TOGGLE
    initial: true
  power_panels:
    name: Power Panels    ###  ENERGY/POWER TOGGLE
    initial: true

command_line:
  - sensor:
      name: timelapse_power_graph   ### GRAPH sensor
      command: "cat /config/power/graph.json"   ### MUST MATCH ${DATA_DIR} in panels_query.sh
      value_template: "{{ value_json.values[0] }}"
      json_attributes:
        - values
      scan_interval: 99999
  - sensor:
      name: timelapse_power_panels   ### PANELS + POWE METER, all of them, are a single sensor, in json attributes
      command: "cat /config/power/panels.json"   ### MUST MATCH ${DATA_DIR} in panels_query.sh
      scan_interval: 99999
      value_template: "{{ value_json.power }}"
      json_attributes:
        - inverter_e00122xxxxxxxxxx_lifetime_power
        - inverter_e00122xxxxxxxxxx_lifetime_power   ### replace these attributes with the output of /config/scripts/query_panels.sh --discover or output in /config/power/entities.txt
        - inverter_e00122xxxxxxxxxx_lifetime_power   ### each needs to be associated with a panel in dashboard.yaml
        - power_meter_pvs6mxxxxxxxxp_lifetime_power

shell_command:   ### call to query_panels.sh script
  query_panels: "/config/scripts/query_panels.sh -d {{ day }} -h {{ hour }} -m {{ mode }}"
